version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: vaadinstart
      POSTGRES_PASSWORD: vaadinstart
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: vaadin-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/vaadinstart
      SPRING_DATASOURCE_USERNAME: vaadinstart
      SPRING_DATASOURCE_PASSWORD: vaadinstart
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pg_data:
